services:
  - type: web
    name: seu-app-php
    runtime: php
    buildCommand: |
      # Cria a estrutura de diretórios
      mkdir -p database
      mkdir -p public
      
      # Instala dependências (se tiver composer.json)
      if [ -f "composer.json" ]; then
        composer install --no-interaction --no-dev
      fi
      
      # Configura o banco SQLite
      php setup.php
      
      # Configura permissões (importante para SQLite)
      chmod 755 database
      chmod 644 database/data.db
      
      # Se precisar de migrações adicionais
      # php migrations.php
    startCommand: |
      # Inicia o servidor PHP embutido
      php -S 0.0.0.0:$PORT -t public